num_heads: 8
hidden_dim: 1024
trainable: 3
epochs: 15
batch_size: 16
grad_acc: 32
origins: ['washington_post', 'bbc']
manipulations: ['simswap', 'StyleCLIP']
gpus: [0, 1, 2]
temp: 0.2
momentum: 0.9
queue_size: 32